<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.12.1" name="Level 1" tilewidth="16" tileheight="16" tilecount="110" columns="11">
 <image source="Level 1/Tileset/Tileset.png" width="176" height="160"/>
 <tile id="1" type="Tiles"/>
 <tile id="2" type="Tiles"/>
 <tile id="3" type="Tiles"/>
 <tile id="5" type="Tiles"/>
 <tile id="6" type="Tiles"/>
 <tile id="7" type="Tiles"/>
 <tile id="11" type="Tiles"/>
 <tile id="12" type="Tiles"/>
 <tile id="13" type="Tiles"/>
 <tile id="14" type="Tiles"/>
 <tile id="15" type="Tiles"/>
 <tile id="16" type="Tiles"/>
 <tile id="19" type="Tiles"/>
 <tile id="20" type="Tiles"/>
 <tile id="21" type="Tiles"/>
 <tile id="22" type="Tiles"/>
 <tile id="23" type="Tiles"/>
 <tile id="24" type="Tiles"/>
 <tile id="25" type="Tiles"/>
 <tile id="26" type="Tiles"/>
 <tile id="28" type="Tiles"/>
 <tile id="29" type="Tiles"/>
 <tile id="30" type="Tiles"/>
 <tile id="31" type="Tiles"/>
 <tile id="32" type="Tiles"/>
 <tile id="33" type="Tiles"/>
 <tile id="34" type="Tiles"/>
 <tile id="35" type="Tiles"/>
 <tile id="36" type="Tiles"/>
 <tile id="37" type="Tiles"/>
 <tile id="39" type="Tiles"/>
 <tile id="45" type="Tiles"/>
 <tile id="46" type="Tiles"/>
 <tile id="47" type="Tiles"/>
 <tile id="50" type="Tiles"/>
 <tile id="56" type="Tiles"/>
 <tile id="57" type="Tiles"/>
 <tile id="58" type="Tiles"/>
 <tile id="66" type="Tiles"/>
 <tile id="67" type="Tiles"/>
 <tile id="68" type="Tiles"/>
 <tile id="69" type="Tiles"/>
 <tile id="70" type="Tiles"/>
 <tile id="77" type="Tiles"/>
 <tile id="78" type="Tiles"/>
 <tile id="79" type="Tiles"/>
 <tile id="80" type="Tiles"/>
 <tile id="81" type="Tiles"/>
 <tile id="88" type="Tiles"/>
 <tile id="89" type="Tiles"/>
 <tile id="90" type="Tiles"/>
 <tile id="91" type="Tiles"/>
 <tile id="92" type="Tiles"/>
 <tile id="100" type="Tiles"/>
 <tile id="101" type="Tiles"/>
 <tile id="102" type="Tiles"/>
</tileset>
