<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.12.1" name="Tilesetv3" tilewidth="16" tileheight="16" tilecount="884" columns="17">
 <image source="../Background For Levels/Level 2/Tilesetv3.png" width="272" height="832"/>
 <tile id="19" type="Tiles"/>
 <tile id="20" type="Tiles"/>
 <tile id="34" type="Tiles"/>
 <tile id="35" type="Tiles"/>
 <tile id="36" type="Tiles"/>
 <tile id="37" type="Tiles"/>
 <tile id="38" type="Tiles"/>
 <tile id="51" type="Tiles"/>
 <tile id="52" type="Tiles"/>
 <tile id="53" type="Tiles"/>
 <tile id="54" type="Tiles"/>
 <tile id="55" type="Tiles"/>
 <tile id="68" type="Tiles"/>
 <tile id="69" type="Tiles"/>
 <tile id="70" type="Tiles"/>
 <tile id="71" type="Tiles"/>
 <tile id="72" type="Tiles"/>
 <tile id="85" type="Tiles"/>
 <tile id="86" type="Tiles"/>
 <tile id="87" type="Tiles"/>
 <tile id="88" type="Tiles"/>
 <tile id="89" type="Tiles"/>
 <tile id="102" type="Tiles"/>
 <tile id="103" type="Tiles"/>
 <tile id="121" type="Tiles"/>
 <tile id="122" type="Tiles"/>
 <tile id="136" type="Tiles"/>
 <tile id="137" type="Tiles"/>
 <tile id="138" type="Tiles"/>
 <tile id="139" type="Tiles"/>
 <tile id="140" type="Tiles"/>
 <tile id="153" type="Tiles"/>
 <tile id="154" type="Tiles"/>
 <tile id="155" type="Tiles"/>
 <tile id="156" type="Tiles"/>
 <tile id="157" type="Tiles"/>
 <tile id="170" type="Tiles"/>
 <tile id="171" type="Tiles"/>
 <tile id="172" type="Tiles"/>
 <tile id="173" type="Tiles"/>
 <tile id="174" type="Tiles"/>
 <tile id="187" type="Tiles"/>
 <tile id="188" type="Tiles"/>
 <tile id="189" type="Tiles"/>
 <tile id="190" type="Tiles"/>
 <tile id="191" type="Tiles"/>
 <tile id="204" type="Tiles"/>
 <tile id="206" type="Tiles"/>
 <tile id="207" type="Tiles"/>
 <tile id="223" type="Tiles"/>
 <tile id="224" type="Tiles"/>
 <tile id="238" type="Tiles"/>
 <tile id="239" type="Tiles"/>
 <tile id="240" type="Tiles"/>
 <tile id="241" type="Tiles"/>
 <tile id="242" type="Tiles"/>
 <tile id="255" type="Tiles"/>
 <tile id="256" type="Tiles"/>
 <tile id="257" type="Tiles"/>
 <tile id="258" type="Tiles"/>
 <tile id="259" type="Tiles"/>
 <tile id="272" type="Tiles"/>
 <tile id="273" type="Tiles"/>
 <tile id="274" type="Tiles"/>
 <tile id="275" type="Tiles"/>
 <tile id="276" type="Tiles"/>
 <tile id="289" type="Tiles"/>
 <tile id="290" type="Tiles"/>
 <tile id="291" type="Tiles"/>
 <tile id="292" type="Tiles"/>
 <tile id="293" type="Tiles"/>
 <tile id="308" type="Tiles"/>
 <tile id="309" type="Tiles"/>
 <tile id="325" type="Tiles"/>
 <tile id="326" type="Tiles"/>
 <tile id="340" type="Tiles"/>
 <tile id="341" type="Tiles"/>
 <tile id="342" type="Tiles"/>
 <tile id="343" type="Tiles"/>
 <tile id="344" type="Tiles"/>
 <tile id="357" type="Tiles"/>
 <tile id="358" type="Tiles"/>
 <tile id="359" type="Tiles"/>
 <tile id="360" type="Tiles"/>
 <tile id="361" type="Tiles"/>
 <tile id="374" type="Tiles"/>
 <tile id="375" type="Tiles"/>
 <tile id="376" type="Tiles"/>
 <tile id="377" type="Tiles"/>
 <tile id="378" type="Tiles"/>
 <tile id="391" type="Tiles"/>
 <tile id="392" type="Tiles"/>
 <tile id="393" type="Tiles"/>
 <tile id="394" type="Tiles"/>
 <tile id="395" type="Tiles"/>
 <tile id="410" type="Tiles"/>
 <tile id="411" type="Tiles"/>
</tileset>
